# Generated by Django 4.2.1 on 2023-05-16 06:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='body',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
