# Generated by Django 4.2.1 on 2023-06-09 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('start_time', models.DateTimeField(verbose_name='Начинается')),
                ('end_time', models.DateTimeField(verbose_name='Завершается')),
                ('students', models.ManyToManyField(blank=True, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Студенты')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начинается')),
                ('end_time', models.DateTimeField(verbose_name='Завершается')),
                ('title', models.CharField(max_length=1000, verbose_name='Тема урока')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='Вопрос')),
                ('type_t', models.CharField(choices=[('Test', 'Test'), ('Question', 'Question')], default='Test', max_length=1000, verbose_name='Тип заданий')),
                ('true_answer', models.CharField(blank=True, max_length=200, verbose_name='Правильный вариант')),
                ('false_answer_1', models.CharField(blank=True, max_length=200, verbose_name='Дополнительный вариант 1')),
                ('false_answer_2', models.CharField(blank=True, max_length=200, verbose_name='Дополнительный вариант 2')),
                ('false_answer_3', models.CharField(blank=True, max_length=200, verbose_name='Дополнительный вариант 3')),
                ('answer', models.CharField(blank=True, max_length=200, verbose_name='Правильный ответ')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Заданий',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Содержимое')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекций',
            },
        ),
    ]
