# Generated by Django 4.2.1 on 2023-06-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_teacher_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
