# Generated by Django 4.2.1 on 2023-05-17 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(verbose_name='Адрес почты')),
                ('send_datetime', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
            ],
        ),
    ]
