# Generated by Django 4.2.1 on 2023-05-17 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(validators=[members.models.validate_phone_number])),
                ('user_role', models.CharField(choices=[('Студент', 'Студент'), ('Преподаватель', 'Преподаватель'), ('Супер админ', 'Супер админ'), ('Админ', 'Админ')], default='Студент', max_length=15, null=True, verbose_name='Статус пользователья')),
                ('birth_day', models.DateTimeField(verbose_name='Дата рождение')),
                ('biography', models.CharField(blank=True, max_length=250, verbose_name='О себе')),
                ('user_ip', models.CharField(blank=True, max_length=100, verbose_name='IP')),
                ('address', models.CharField(blank=True, max_length=90, verbose_name='Адрес')),
                ('mail_index', models.CharField(blank=True, max_length=15, verbose_name='Индекс почты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
