# Generated by Django 4.2.1 on 2023-06-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_usercustomer_age_usercustomer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomer',
            name='birth_day',
            field=models.DateField(verbose_name='Дата рождение'),
        ),
    ]
