# Generated by Django 4.2.1 on 2023-06-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_usercustomer_birth_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustomer',
            options={'verbose_name': 'Дополнительный данный', 'verbose_name_plural': 'Дополнительные данные'},
        ),
    ]
